name: Deploy CI
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: TNd54eKS2vrugPqdnLUQkL2s
          VERCEL_PROJECT_ID: prj_s75iq48oJghDGQg3qktZpFo7E7G9